"""db test

Revision ID: 1315c9da6eb8
Revises: 451d01f3f89f
Create Date: 2024-08-20 00:31:46.601708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1315c9da6eb8'
down_revision: Union[str, None] = '451d01f3f89f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skillcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill',
    sa.Column('uu_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['skillcategory.id'], ),
    sa.PrimaryKeyConstraint('uu_id', 'id')
    )
    op.create_index(op.f('ix_skill_uu_id'), 'skill', ['uu_id'], unique=False)
    op.add_column('profile', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'user_id')
    op.drop_index(op.f('ix_skill_uu_id'), table_name='skill')
    op.drop_table('skill')
    op.drop_table('skillcategory')
    # ### end Alembic commands ###
