"""empty message

Revision ID: 59fcb68bf5f1
Revises: 20fa9ee63771
Create Date: 2024-10-30 21:25:48.122694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59fcb68bf5f1'
down_revision: Union[str, None] = '20fa9ee63771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pulse_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pulse', sa.Column('blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pulse', 'blocked')
    op.drop_table('complaints')
    # ### end Alembic commands ###
