"""empty message

Revision ID: bb1770152441
Revises: a35aaa3b7706
Create Date: 2024-09-14 20:35:39.942886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb1770152441'
down_revision: Union[str, None] = 'a35aaa3b7706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pulse', 'image')
    op.drop_column('pulse', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pulse', sa.Column('tags', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('pulse', sa.Column('image', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
