"""empty message

Revision ID: a7b47b227ddd
Revises: 45bb59cb3056
Create Date: 2024-10-28 00:50:50.899838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b47b227ddd'
down_revision: Union[str, None] = '45bb59cb3056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('images_pulse_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'pulse', ['pulse_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_pulse_id_fkey', 'images', 'pulse', ['pulse_id'], ['id'])
    # ### end Alembic commands ###
