"""empty message

Revision ID: da10cdb9c2b7
Revises: fe1fe7e83eab
Create Date: 2024-08-21 18:10:08.582247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'da10cdb9c2b7'
down_revision: Union[str, None] = 'fe1fe7e83eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('application_project_id_fkey', 'application', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('application_project_id_fkey', 'application', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###
