"""empty message

Revision ID: b12c4943b3e9
Revises: 4546ea6c4d8a
Create Date: 2024-09-17 15:36:43.019161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b12c4943b3e9'
down_revision: Union[str, None] = '4546ea6c4d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('pulse_id', sa.Integer(), nullable=True))
    op.drop_column('application', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('application', 'pulse_id')
    # ### end Alembic commands ###
