"""empty message

Revision ID: 0fd669ba1047
Revises: ad70fc4de930
Create Date: 2024-11-04 23:40:42.650753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fd669ba1047'
down_revision: Union[str, None] = 'ad70fc4de930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('complaints', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'updated_at')
    op.drop_column('complaints', 'created_at')
    # ### end Alembic commands ###
