"""file_uploader

Revision ID: 9313c4f829a8
Revises: 6dd69b84f9ec
Create Date: 2024-10-19 21:05:55.583531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9313c4f829a8'
down_revision: Union[str, None] = '6dd69b84f9ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('pulse_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.drop_table('images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('image_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pulse_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('image_id', name='images_pkey')
    )
    op.drop_table('files')
    # ### end Alembic commands ###
