"""empty message

Revision ID: ce38efe4ad85
Revises: 9313c4f829a8
Create Date: 2024-10-19 23:53:51.029561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce38efe4ad85'
down_revision: Union[str, None] = '9313c4f829a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('pulse_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pulse_id'], ['pulse.id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_foreign_key(None, 'files', 'pulse', ['pulse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_table('images')
    # ### end Alembic commands ###
