"""empty message

Revision ID: 86f3d29f5ccc
Revises: bb1770152441
Create Date: 2024-09-14 20:37:04.452440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f3d29f5ccc'
down_revision: Union[str, None] = 'bb1770152441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pulse', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('pulse', sa.Column('image', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pulse', 'image')
    op.drop_column('pulse', 'tags')
    # ### end Alembic commands ###
