"""empty message

Revision ID: 5a7bae2f0ed7
Revises: bfaa5c06e176
Create Date: 2024-09-14 13:58:29.281772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7bae2f0ed7'
down_revision: Union[str, None] = 'bfaa5c06e176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
