"""empty message

Revision ID: 99b740a3fa8a
Revises: ec991b4c91d7
Create Date: 2024-10-20 13:21:05.011322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b740a3fa8a'
down_revision: Union[str, None] = 'ec991b4c91d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'decription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('decription', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
