"""empty message

Revision ID: b9434025efcd
Revises: cf87e329ce17
Create Date: 2024-10-21 14:34:41.581673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9434025efcd'
down_revision: Union[str, None] = 'cf87e329ce17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pulse_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pulse_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pulse', sa.Column('founder_id', sa.Integer(), nullable=True))
    op.add_column('tag', sa.Column('decription', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'decription')
    op.drop_column('pulse', 'founder_id')
    op.drop_table('pulse_members')
    # ### end Alembic commands ###
