"""empty message

Revision ID: 4537c6cae79f
Revises: 86f3d29f5ccc
Create Date: 2024-09-14 21:42:05.360288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4537c6cae79f'
down_revision: Union[str, None] = '86f3d29f5ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pulse_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pulse_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('pulse', 'tags')
    op.drop_column('pulse', 'image')
    op.add_column('tag', sa.Column('decription', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'decription')
    op.add_column('pulse', sa.Column('image', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('pulse', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('pulse_tags')
    # ### end Alembic commands ###
