"""empty message

Revision ID: 7eeb6f11272a
Revises: 
Create Date: 2024-09-14 12:41:13.211587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eeb6f11272a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pulse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catrgory', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('decription', sa.String(), nullable=True),
    sa.Column('short_decription', sa.String(), nullable=True),
    sa.Column('image', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pulse')
    # ### end Alembic commands ###
