"""empty message

Revision ID: 03334017eb5f
Revises: a7b47b227ddd
Create Date: 2024-10-29 02:18:06.335394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03334017eb5f'
down_revision: Union[str, None] = 'a7b47b227ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('application', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('images', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    op.add_column('pulse', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('pulse', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pulse', 'updated_at')
    op.drop_column('pulse', 'created_at')
    op.drop_column('images', 'uploaded_at')
    op.drop_column('application', 'updated_at')
    op.drop_column('application', 'created_at')
    # ### end Alembic commands ###
