"""empty message

Revision ID: 12c86fa34ee5
Revises: 03e2b5a85225
Create Date: 2024-11-09 03:46:27.619853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c86fa34ee5'
down_revision: Union[str, None] = '03e2b5a85225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pulse_members', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_column('pulse_members', 'tag_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pulse_members', sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('pulse_members', 'user_id')
    # ### end Alembic commands ###
